-- MySQL Script generated by MySQL Workbench
-- Fri Jun 15 11:39:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `id_utilisateur` INT(255) NOT NULL AUTO_INCREMENT,
  `nom_utilisateur` VARCHAR(45) NOT NULL,
  `mot_de_passe` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_utilisateur`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`administration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`administration` (
  `id_administration` INT(100) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `utilisateur_id_utilisateur` INT(255) NOT NULL,
  PRIMARY KEY (`id_administration`, `utilisateur_id_utilisateur`),
  INDEX `fk_administration_utilisateur1_idx` (`utilisateur_id_utilisateur` ASC),
  CONSTRAINT `fk_administration_utilisateur1`
    FOREIGN KEY (`utilisateur_id_utilisateur`)
    REFERENCES `mydb`.`utilisateur` (`id_utilisateur`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id_client` INT(100) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `numero_telephone` INT(10) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `utilisateur_id_utilisateur` INT(255) NOT NULL,
  PRIMARY KEY (`id_client`, `utilisateur_id_utilisateur`),
  INDEX `fk_client_utilisateur1_idx` (`utilisateur_id_utilisateur` ASC),
  CONSTRAINT `fk_client_utilisateur1`
    FOREIGN KEY (`utilisateur_id_utilisateur`)
    REFERENCES `mydb`.`utilisateur` (`id_utilisateur`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`adresse_livraison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adresse_livraison` (
  `id_adresse_livraison` INT(100) NOT NULL AUTO_INCREMENT,
  `voie` VARCHAR(100) NOT NULL,
  `complement_construction` VARCHAR(100) NULL DEFAULT NULL,
  `complement_adresse` VARCHAR(100) NULL DEFAULT NULL,
  `code_postale` INT(5) NOT NULL,
  `localite` VARCHAR(45) NOT NULL,
  `geo_localisation` VARCHAR(10) NOT NULL,
  `client_id_client` INT(100) NOT NULL,
  PRIMARY KEY (`id_adresse_livraison`, `client_id_client`),
  INDEX `fk_adresse_livraison_client1_idx` (`client_id_client` ASC),
  CONSTRAINT `fk_adresse_livraison_client1`
    FOREIGN KEY (`client_id_client`)
    REFERENCES `mydb`.`client` (`id_client`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`article` (
  `id_article` INT(100) NOT NULL AUTO_INCREMENT,
  `prix_unitaire_ht` DECIMAL(5,2) NOT NULL,
  `taux_tva_100` DOUBLE NOT NULL,
  `descriptif` VARCHAR(255) NOT NULL,
  `stock` INT(255) NOT NULL,
  `nom_type_article` VARCHAR(45) NOT NULL,
  `type_article` VARCHAR(45) NOT NULL,
  `article_au_menu` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id_article`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`facture` (
  `id_facture` INT(11) NOT NULL AUTO_INCREMENT,
  `reference` INT(100) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id_facture`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commande` (
  `id_commande` INT(100) NOT NULL AUTO_INCREMENT,
  `reglement` TINYINT(4) NOT NULL,
  `date` DATETIME NOT NULL,
  `prise_charge` TINYINT(4) NOT NULL,
  `commande_recue` TINYINT(4) NOT NULL,
  `montant` DECIMAL(5,2) NOT NULL,
  `client_id_client` INT(100) NOT NULL,
  `facture_id_facture` INT(11) NOT NULL,
  PRIMARY KEY (`id_commande`, `client_id_client`, `facture_id_facture`),
  INDEX `fk_commande_client1_idx` (`client_id_client` ASC),
  INDEX `fk_commande_facture1_idx` (`facture_id_facture` ASC),
  CONSTRAINT `fk_commande_client1`
    FOREIGN KEY (`client_id_client`)
    REFERENCES `mydb`.`client` (`id_client`),
  CONSTRAINT `fk_commande_facture1`
    FOREIGN KEY (`facture_id_facture`)
    REFERENCES `mydb`.`facture` (`id_facture`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`ligne_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ligne_commande` (
  `commande_id_commande` INT(100) NOT NULL,
  `article_id_article` INT(100) NOT NULL,
  `quantite` INT(100) NOT NULL,
  PRIMARY KEY (`commande_id_commande`, `article_id_article`),
  INDEX `fk_commande_has_article_article1_idx` (`article_id_article` ASC),
  INDEX `fk_commande_has_article_commande1_idx` (`commande_id_commande` ASC),
  CONSTRAINT `fk_ligne_commande_article1`
    FOREIGN KEY (`article_id_article`)
    REFERENCES `mydb`.`article` (`id_article`),
  CONSTRAINT `fk_ligne_commande_commande1`
    FOREIGN KEY (`commande_id_commande`)
    REFERENCES `mydb`.`commande` (`id_commande`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`livreur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livreur` (
  `id_livreur` INT(100) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `statut_disponible` TINYINT(4) NOT NULL,
  `geo_localisation` VARCHAR(10) NOT NULL,
  `utilisateur_id_utilisateur` INT(255) NOT NULL,
  PRIMARY KEY (`id_livreur`, `utilisateur_id_utilisateur`),
  INDEX `fk_livreur_utilisateur1_idx` (`utilisateur_id_utilisateur` ASC),
  CONSTRAINT `fk_livreur_utilisateur1`
    FOREIGN KEY (`utilisateur_id_utilisateur`)
    REFERENCES `mydb`.`utilisateur` (`id_utilisateur`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`livraison_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livraison_commande` (
  `livreur_id_livreur` INT(100) NOT NULL,
  `commande_id_commande` INT(100) NOT NULL,
  `temps_livraison` DATETIME NOT NULL,
  PRIMARY KEY (`livreur_id_livreur`, `commande_id_commande`),
  INDEX `fk_livreur_has_commande_commande1_idx` (`commande_id_commande` ASC),
  INDEX `fk_livreur_has_commande_livreur1_idx` (`livreur_id_livreur` ASC),
  CONSTRAINT `fk_livraison_commande_commande1`
    FOREIGN KEY (`commande_id_commande`)
    REFERENCES `mydb`.`commande` (`id_commande`),
  CONSTRAINT `fk_livraison_commande_livreur1`
    FOREIGN KEY (`livreur_id_livreur`)
    REFERENCES `mydb`.`livreur` (`id_livreur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`sac_livreur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sac_livreur` (
  `article_id_article` INT(100) NOT NULL,
  `livreur_id_livreur` INT(100) NOT NULL,
  `quantite` INT(100) NOT NULL,
  PRIMARY KEY (`article_id_article`, `livreur_id_livreur`),
  INDEX `fk_article_has_livreur_livreur1_idx` (`livreur_id_livreur` ASC),
  INDEX `fk_article_has_livreur_article1_idx` (`article_id_article` ASC),
  CONSTRAINT `fk_sac_livreur_article1`
    FOREIGN KEY (`article_id_article`)
    REFERENCES `mydb`.`article` (`id_article`),
  CONSTRAINT `fk_sac_livreur_livreur1`
    FOREIGN KEY (`livreur_id_livreur`)
    REFERENCES `mydb`.`livreur` (`id_livreur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
